swagger: '2.0'
info:
  version: '1'
  title: ''
  description: ''
paths: {}
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /TESTINGPROFILEDEV_1/Userinfo-service/1
schemes:
 - https