{
  "swagger" : "2.0",
  "info" : {
    "description" : "",
    "version" : "1",
    "title" : ""
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/TESTINGPROFILEDEV_1/Userinfo-service/1",
  "schemes" : [ "https" ],
  "paths" : { }
}